name: synthpic
channels:
- defaults
- conda-forge
- kitsune.one
dependencies:
- python
- trimesh
- numpy
- matplotlib
- jupyter
- jupytext
- ipympl
- pillow
- seaborn
- pandas
- scikit-image
- imgaug
- noise
- pip
- pip:
    - pyrender